version: "3.8"

services:
  jcfa-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: jcfa-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - jcfa-mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - jcfa-network
    volumes:
      - ./app:/app

  jcfa-mongodb:
    image: mongo:5.0
    container_name: jcfa-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db

volumes:
  db_data:

networks:
  jcfa-network:
