version: "3.8"

services:
  jcfa-app:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.12
    container_name: jcfa-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - jcfa-network
    volumes:
      - ./app:/app

volumes:
  db_data:

networks:
  jcfa-network:
